### ISSUE TITLE
handleNewLine throws error when pressing enter at the end of a code block

### ISSUE THREAD

**Issue by thibaudcolas** [jpuri/draftjs-utils#10]
Here is a demo reproducing the issue, as well as a GIF:

https://jsfiddle.net/thibaudcolas/Lo2zL37h/

![draftjs-utils-code-block-error](https://user-images.githubusercontent.com/877585/33474858-e21f82b4-d684-11e7-9d4f-2ece9cfa03ca.gif)

I could track this down to `removeSelectedBlocksStyle`:

https://github.com/jpuri/draftjs-utils/blob/112bbe449cc9156522fcf2b40f2910a071b795c2/js/block.js#L94-L101

The error is because `tryToRemoveBlockStyle` returns `null` within `code-block` (https://github.com/facebook/draft-js/blob/548fd5d1b1c31b7b4c79cd70b101fae69d522b3f/src/model/modifier/RichTextEditorUtil.js#L389-L396).

----

I think `removeSelectedBlockStyle` should at least handle this gracefully, something like:

```js
export function removeSelectedBlocksStyle(editorState: EditorState): EditorState { 
  const newContentState = RichUtils.tryToRemoveBlockStyle(editorState); 
  if (newContentState) {
    return EditorState.push(editorState, newContentState, 'change-block-type');
  }
  return editorState;
} 
```

For the purpose of `handleNewLine`, the above wouldn't do anything on return though, which still isn't the right behaviour. Here is what I did in my code (not fully tested yet):

```js
/**
 * Rely on DraftUtils for soft newlines, and hard newlines that do not fall
 * in the special "defer breaking out of the block" case.
 */
handleNewLine(editorState, event) {
    if (isSoftNewlineEvent(event)) {
        return DraftUtils.handleNewLine(editorState, event);
    }

    const content = editorState.getCurrentContent();
    const selection = editorState.getSelection();
    const key = selection.getStartKey();
    const offset = selection.getStartOffset();
    const block = content.getBlockForKey(key);

    const isDeferredBreakoutBlock = ['code-block'].includes(
        block.getType(),
    );

    if (isDeferredBreakoutBlock) {
        const isEmpty =
            selection.isCollapsed() &&
            offset === 0 &&
            block.getLength() === 0;

        if (isEmpty) {
            return EditorState.push(
                editorState,
                Modifier.setBlockType(content, selection, 'unstyled'),
                'change-block-type',
            );
        }

        return false;
    }

    return DraftUtils.handleNewLine(editorState, event);
},
```

![draftjs-utils-code-block-solution](https://user-images.githubusercontent.com/877585/33475767-4259e95a-d688-11e7-83c3-7ac056b0a202.gif)

I'm happy to submit a PR if this looks like a suitable solution.

**Comment by aravindballa** [comment]
Thanks for raising this issue. It helped me in fixing mine. 🤓 

Although, I had to make a small change in the code from your fiddle.

```js
handleReturn(e) {
  	const { editorState } = this.state;
    const newState = DraftUtils.handleNewLine(editorState, e);
    if (newState) {
      this._handleChange(newState);
      return 'handled';
    }
    
    return 'not-handled';
  }
```

**Comment by jpuri** [comment]
Ah sorry for missing this out. I will fix this soon in the lib. Thanks @thibaudcolas

**Comment by jpuri** [comment]
`draftjs-utils@0.9.3` has the fix.
