### ISSUE TITLE
How to add custom inline styles for font-weight, letter-spacing, etc...

### ISSUE THREAD

**Issue by DaisukeKajiyama** [jpuri/draftjs-utils#17]
Hey I'm having trouble figuring out how ``toggleCustomInlineStyle`` works.

I was successfully able to change the inline font-size by doing something like:
```
const newEditorState = toggleCustomInlineStyle(figure.editorState, 'fontSize', e.target.value);
this.setState({editorState: newEditorState})
```

but then when I wanted to do the same thing with font-weight, letter-spacing, etc... it doesn't work.
Is this function not supported? If so, how can I achieve it?

**Comment by jpuri** [comment]
Hey @DaisukeKajiyama , custom styles supported atm are: https://github.com/jpuri/draftjs-utils/blob/master/js/inline.js#L130

You can use this method directly to add other inline styles: https://draftjs.org/docs/api-reference-rich-utils#toggleinlinestyle

You will also be required to add it here: `customStyleMap`
https://draftjs.org/docs/advanced-topics-inline-styles#mapping-a-style-string-to-css

**Comment by DaisukeKajiyama** [comment]
@jpuri Thanks! I managed to do it
