### ISSUE TITLE
draftjs-utils doesn't exist

### ISSUE THREAD

**Issue by geac** [jpuri/draftjs-utils#6]
trying to npm install or yarn install on https://github.com/zuiidea/antd-admin
gives me:

on npm:
```
npm ERR! addLocal Could not install xxx/node_modules/draftjs-utils
```
on yarn:

```
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error "xxx/draftjs-utils" doesn't exist.
```

I think this is related to recent new release from your packages

**Comment by jpuri** [comment]
@geac , I guess you are using editor. Plz try with latest version of the editor react-draft-wysiwyg.

**Comment by jpuri** [comment]
Ref: https://github.com/jpuri/react-draft-wysiwyg/issues/385
