### ISSUE TITLE
Uncaught TypeError: e.indexOf is not a function

### ISSUE THREAD

**Issue by huadong** [jpuri/draftjs-utils#7]
Exception in inline.js line 240 of commit: 98d5c660c2d899f4242ac68230a4c2fa0e7850ef

```javascript
export function extractInlineStyle(editorState) {
  if(editorState) {
    const styleList = editorState.getCurrentContent().getBlockMap().map(block => block.get('characterList')).toList().flatten();
    styleList.forEach(style => {
      if (style && style.indexOf('color-') === 0) {
        addToCustomStyleMap('color', 'color', style.substr(6));
      } else if (style && style.indexOf('bgcolor-') === 0) {
        addToCustomStyleMap('bgcolor', 'backgroundColor', style.substr(8));
      } else if (style && style.indexOf('fontsize-') === 0) {
        addToCustomStyleMap('fontSize', 'fontSize', style.substr(9));
      } else if (style && style.indexOf('fontfamily-') === 0) {
        addToCustomStyleMap('fontFamily', 'fontFamily', style.substr(11));
      }
    });
  }
}
```
does
`
editorState.getCurrentContent().getBlockMap().map(block => block.get('characterList')).toList().flatten();
`
return `Array<string>` ?

I am a newbie.

**Comment by jpuri** [comment]
Hi @huadong : it will return an array of inline styles like ['color', 'bgcolor', ...]

I hope I understood your question correctly 😄

**Comment by jpuri** [comment]
Ah also note that now `immutableJS` is a peer dependency for draftjs-utils. Ensure its present in your project.

**Comment by huadong** [comment]
Fixed. Maybe the external modules fire this exception, After I update all the dependence modules base on draftjs-utils, it works fine.

Thanks a lot @jpuri .
